name: 'install-git-chglog'
description: 'GitHub Action for git-chglog. Anytime, anywhere, Write your CHANGELOG.'
author: 'craicoverflow'
branding:
  color: 'green'
  icon: 'package'

inputs:
  version:
    description: 'Specify which git-chglog version to use'
    default: 'latest'
    required: false

runs:
  using: 'node12'
  main: 'dist/index.js'